# Site info
title: Jasper
description: >-
  Transform your plain text into static websites and blogs.
logo:
url: https://gitlab.com/mittalyashu/jasper

# Site variable
cover_image: assets/images/blog-cover.jpg
subscribe: true
tooltip: true
author_image: false
author_image_placeholder: image

# Social media
facebook_username: codecarrotinc
twitter_username: codecarrotnet
disqus: false
disqus_shortname:
google_analytics: true
ga_tracking: UA-123746316-1

# Jekyll settings
baseurl: /jasper/
markdown: kramdown
theme: jasper-theme
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git
  - LICENSE
